# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bangela <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/08/23 15:53:10 by bangela           #+#    #+#              #
#    Updated: 2018/08/24 15:36:51 by bangela          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
FILES = ft_display_file.c
OBJ = ft_display_file.o

all: 
	gcc -c -Wall -Wextra -Werror $(FILES)
	gcc -o $(NAME) $(OBJ)
clean:
	rm -f $(OBJ)
fclean: clean
	rm -f $(NAME)
